name = "DifferentiableEigen"
uuid = "73a20539-4e65-4dcb-a56d-dc20f210a01b"
authors = ["TT <tobias.thummerer@informatik.uni-augsburg.de>", "LM <lars.mikelsons@informatik.uni-augsburg.de>"]
version = "0.1.0"

[deps]
ForwardDiffChainRules = "c9556dd2-1aed-4cfe-8560-1557cf593001"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ForwardDiffChainRules = "0.1"
julia = "1.6"
